version: '3.8'
services:
  male_uav_frontend:
    build:
      context: ./male_uav_frontend-
      dockerfile: Dockerfile
    container_name: drdo_uav_frontend
    ports:
    - 3000:3000
    environment:
    - VITE_API_URL=http://localhost:8000
    - VITE_WS_URL=ws://localhost:8000/ws
    networks:
    - drdo_gcs_network
    depends_on:
    - backend-service
    restart: unless-stopped
  simulator-service:
    build:
      context: ./simulator
      dockerfile: Dockerfile
    container_name: drdo_simulator_service
    ports:
    - 5001:5001
    environment:
    - SIMULATION_FREQUENCY_HZ=20
    - BROKER_URL=redis://database_cache:6379/0
    networks:
    - drdo_gcs_network
    depends_on:
    - database
    restart: unless-stopped
  backend-service:
    build:
      context: ./backend-service
      dockerfile: Dockerfile
    container_name: drdo_backend_service
    ports:
    - 8000:8000
    environment:
    - DATABASE_URL=postgres://drdo_admin:drdo_secure_pass@database_timescale:5432/uav_telemetry
    - REDIS_URL=redis://database_cache:6379/0
    - AI_SERVICE_URL=http://ai-service:5000
    - TWIN_SERVICE_URL=http://digital-twin-service:5002
    networks:
    - drdo_gcs_network
    depends_on:
    - database
    - simulator-service
    restart: unless-stopped
  ai-service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile
    container_name: drdo_ai_service
    ports:
    - 5000:5000
    environment:
    - MODEL_VERSION=v4.2.8
    - REDIS_URL=redis://database_cache:6379/0
    networks:
    - drdo_gcs_network
    depends_on:
    - database
    restart: unless-stopped
  database:
    image: timescale/timescaledb:latest-pg15
    container_name: drdo_database_timescale
    ports:
    - 5432:5432
    environment:
    - POSTGRES_DB=uav_telemetry
    - POSTGRES_USER=drdo_admin
    - POSTGRES_PASSWORD=drdo_secure_pass
    volumes:
    - timescale_data:/var/lib/postgresql/data
    - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
    - drdo_gcs_network
    restart: unless-stopped
  database_cache:
    image: redis:7-alpine
    container_name: drdo_database_cache
    ports:
    - 6379:6379
    networks:
    - drdo_gcs_network
    restart: unless-stopped
  px4-sitl:
    build:
      context: ./px4-sitl
      dockerfile: Dockerfile
    container_name: px4_sitl
    ports:
    - "14550:14550/udp"
    networks:
    - drdo_gcs_network
    restart: unless-stopped
  mavlink-bridge:
    build:
      context: ./mavlink-bridge
      dockerfile: Dockerfile
    container_name: mavlink_bridge
    environment:
    - BACKEND_WS_URL=ws://backend-service:8000/ws/telemetry_ingest
    - MAVLINK_URI=udpout:px4-sitl:14550
    networks:
    - drdo_gcs_network
    depends_on:
    - px4-sitl
    - backend-service
    restart: unless-stopped
networks:
  drdo_gcs_network:
    driver: bridge
volumes:
  timescale_data: null
