import { UavUnit, MissionProfile, InjectedFault, AlertNotification, DemoTourStep } from '../types';

export const GCS_VERSION = 'DRDO-GCS-DT-v4.2.8-CLASSIFIED';
export const FACILITY_NAME = 'AERONAUTICAL DEVELOPMENT ESTABLISHMENT (ADE) - DRDO';
export const COMMAND_CENTER = 'GROUND CONTROL STATION #03 (COMMAND & TELEMETRY NODE)';

export const NAV_ITEMS = [
  { id: 'dashboard', label: 'Mission Overview', path: '/', icon: 'LayoutDashboard', badge: 'LIVE' },
  { id: 'live-monitoring', label: 'Live Telemetry', path: '/live-monitoring', icon: 'Activity', badge: 'SCADA' },
  { id: 'digital-twin', label: '3D Digital Twin', path: '/digital-twin', icon: 'Cpu', badge: '3D/HEAT' },
  { id: 'ai-predictions', label: 'AI Prediction Center', path: '/ai-predictions', icon: 'BrainCircuit', badge: 'RUL/XAI' },
  { id: 'hybrid-verification', label: 'Physics + AI Hybrid', path: '/hybrid-verification', icon: 'GitCompare', badge: 'USP' },
  { id: 'mission-control', label: 'Mission Control', path: '/mission-control', icon: 'Radio', badge: 'GO/NO-GO' },
  { id: 'mission-replay', label: 'Mission Replay', path: '/mission-replay', icon: 'History', badge: 'AI-LOG' },
  { id: 'fault-injection', label: 'Fault Simulator', path: '/fault-injection', icon: 'ZapOff', badge: 'TESTBED' },
  { id: 'maintenance', label: 'Smart Maintenance', path: '/maintenance', icon: 'Wrench', badge: 'LOGBOOK' },
  { id: 'fleet', label: 'Fleet Monitoring', path: '/fleet', icon: 'Radar', badge: '5 UAVs' },
  { id: 'alerts', label: 'Alert & Alarm Center', path: '/alerts', icon: 'AlertTriangle', badge: '3 ACTIVE' },
  { id: 'multi-agent', label: 'Multi-Agent Pipeline', path: '/multi-agent', icon: 'Network', badge: '6 AGENTS' },
  { id: 'continuous-learning', label: 'Continuous Learning', path: '/continuous-learning', icon: 'Sparkles', badge: 'ADAPTIVE' },
  { id: 'reports', label: 'Intelligence Reports', path: '/reports', icon: 'FileText', badge: 'DOCX/PDF' },
  { id: 'system-health', label: 'System Architecture', path: '/system-health', icon: 'ShieldCheck', badge: '99.98%' },
];

export const MOCK_UAV_FLEET: UavUnit[] = [
  {
    id: 'UAV-TAPAS-201',
    callsign: 'TAPAS-BH-201 (GARUDA-1)',
    model: 'DRDO TAPAS-BH-201 MALE UAV',
    serialNumber: 'ADE/MALE/2024/09-201',
    squadron: '144 Squadron "Black Eagles"',
    base: 'Aeronautical Test Range, Chitradurga',
    currentMissionId: 'MSN-IND-7701',
    status: 'ACTIVE_MISSION',
    altitudeFt: 22450,
    airspeedKts: 118,
    fuelRemainingKg: 184.5,
    engineHealthIndex: 88.4,
    missionRiskScore: 18.2,
    twinConfidenceScore: 98.7,
    predictedRulHours: 142.6,
    activeFaultsCount: 0,
    location: {
      lat: 14.2384,
      lng: 76.3982,
      region: 'Chitradurga ATR Sector Echo',
    },
  },
  {
    id: 'UAV-ARCHER-04',
    callsign: 'ARCHER-NG-04 (TRISHUL-2)',
    model: 'DRDO Archer-NG Armed MALE UAV',
    serialNumber: 'ADE/ARM-UAV/2024/04',
    squadron: '22 Tactical Recon Squadron',
    base: 'AFB Jodhpur Sector West',
    currentMissionId: 'MSN-WST-8820',
    status: 'ACTIVE_MISSION',
    altitudeFt: 28500,
    airspeedKts: 134,
    fuelRemainingKg: 210.0,
    engineHealthIndex: 94.2,
    missionRiskScore: 11.5,
    twinConfidenceScore: 99.4,
    predictedRulHours: 218.0,
    activeFaultsCount: 0,
    location: {
      lat: 26.2389,
      lng: 73.0243,
      region: 'Thar Western Border Corridor',
    },
  },
  {
    id: 'UAV-RUSTOM-09',
    callsign: 'RUSTOM-II-09 (VARUNA-4)',
    model: 'DRDO Rustom-II Maritime Recon MALE',
    serialNumber: 'ADE/MAR-UAV/2023/12-09',
    squadron: '312 Naval Air Squadron',
    base: 'INS Hansa, Goa',
    currentMissionId: 'MSN-MAR-5512',
    status: 'ACTIVE_MISSION',
    altitudeFt: 18200,
    airspeedKts: 104,
    fuelRemainingKg: 92.4,
    engineHealthIndex: 72.8,
    missionRiskScore: 38.6,
    twinConfidenceScore: 94.1,
    predictedRulHours: 48.5,
    activeFaultsCount: 1,
    location: {
      lat: 15.3800,
      lng: 73.8300,
      region: 'Arabian Sea EEZ Patrol Zone',
    },
  },
  {
    id: 'UAV-ABHYAS-02',
    callsign: 'ABHYAS-EXP-02 (PINAKA-1)',
    model: 'DRDO High-Speed Target / Engine Testbed',
    serialNumber: 'ADE/TEST-02/2025',
    squadron: 'DRDO Experimental Flight Test Unit',
    base: 'ITR Chandipur, Odisha',
    currentMissionId: 'MSN-EXP-1102',
    status: 'STANDBY',
    altitudeFt: 0,
    airspeedKts: 0,
    fuelRemainingKg: 320.0,
    engineHealthIndex: 97.5,
    missionRiskScore: 4.2,
    twinConfidenceScore: 99.8,
    predictedRulHours: 350.0,
    activeFaultsCount: 0,
    location: {
      lat: 21.4682,
      lng: 87.0125,
      region: 'ITR Range Standby Apron',
    },
  },
  {
    id: 'UAV-SWIFT-07',
    callsign: 'SWIFT-ST-07 (GHATAK-PROTO)',
    model: 'DRDO Stealth Wing Flying Testbed',
    serialNumber: 'ADE/ST-UAV/2025/07',
    squadron: 'Classified Special Projects Wing',
    base: 'Aeronautical Test Range, Challakere',
    currentMissionId: 'MSN-ST-9901',
    status: 'MAINTENANCE',
    altitudeFt: 0,
    airspeedKts: 0,
    fuelRemainingKg: 0,
    engineHealthIndex: 61.3,
    missionRiskScore: 78.4,
    twinConfidenceScore: 91.0,
    predictedRulHours: 12.0,
    activeFaultsCount: 2,
    location: {
      lat: 14.3120,
      lng: 76.6500,
      region: 'ATR Hangar #4 Maintenance Bay',
    },
  },
];

export const MOCK_ACTIVE_MISSION: MissionProfile = {
  id: 'MSN-IND-7701',
  codeName: 'OPERATION INDRADHANUSH - HIGH ALTITUDE PATROL',
  uavId: 'UAV-TAPAS-201',
  phase: 'HIGH_ALT_LOITER',
  startTime: '2026-08-27T06:30:00Z',
  estimatedDurationHours: 18.0,
  elapsedTimeHours: 7.45,
  altitudeFlightLevelFt: 22450,
  terrainType: 'HIGH_ALTITUDE_MOUNTAIN',
  waypoints: [
    { name: 'WP-01 DEPARTURE (ATR)', lat: 14.238, lng: 76.398, altFt: 2500, eta: '06:35Z', status: 'PASSED' },
    { name: 'WP-02 CLIMB CORRIDOR', lat: 14.850, lng: 76.920, altFt: 15000, eta: '07:15Z', status: 'PASSED' },
    { name: 'WP-03 INGRESS NORTH', lat: 15.420, lng: 77.450, altFt: 22000, eta: '08:40Z', status: 'PASSED' },
    { name: 'WP-04 LOITER ORBIT ALPHA', lat: 16.120, lng: 78.100, altFt: 22500, eta: '10:00Z', status: 'CURRENT' },
    { name: 'WP-05 RECON SECTOR BRAVO', lat: 16.850, lng: 78.750, altFt: 23000, eta: '14:30Z', status: 'PENDING' },
    { name: 'WP-06 EGRESS SOUTH', lat: 15.200, lng: 77.100, altFt: 20000, eta: '18:15Z', status: 'PENDING' },
    { name: 'WP-07 RTB RECOVERY', lat: 14.238, lng: 76.398, altFt: 2500, eta: '20:30Z', status: 'PENDING' },
  ],
  goNoGoVerdict: 'GO_MISSION_NORMAL',
  missionRiskIndex: 18.2,
  weatherFactor: {
    oatC: -14.2,
    windSpeedKts: 34,
    densityAltitudeFt: 24800,
    turbulenceLevel: 'MODERATE',
  },
};

export const PRESET_FAULTS: InjectedFault[] = [
  {
    id: 'fault-1',
    type: 'TURBO_WASTEGATE_STUCK',
    name: 'Turbocharger Wastegate Actuator Sticking',
    description: 'Wastegate partially stuck at 35% open position, causing manifold pressure drop and turbo spool oscillation under altitude climb.',
    severityPercent: 65,
    component: 'turbocharger',
    active: false,
    affectedParameters: ['manifoldPressureInHg', 'turbochargerRpm', 'turboBoostBar', 'egtC'],
  },
  {
    id: 'fault-2',
    type: 'INJECTOR_3_CLOGGED',
    name: 'Cylinder #3 Fuel Injector Partial Clog (18% restriction)',
    description: 'Reduced fuel flow to cylinder 3 creating localized lean combustion, spike in Cylinder 3 EGT (+84°C) and micro-vibration harmonics.',
    severityPercent: 78,
    component: 'cylinder_3',
    active: false,
    affectedParameters: ['egtC[2]', 'chtC[2]', 'vibrationFftPeakHz', 'lambdaAirFuelRatio'],
  },
  {
    id: 'fault-3',
    type: 'OIL_PUMP_CAVITATION',
    name: 'Lube Oil Pump Aeration / Cavitation',
    description: 'Cavitation bubbles in scavenge oil circuit during sustained bank angle, causing intermittent oil pressure drops down to 2.1 bar and bearing friction temperature climb.',
    severityPercent: 55,
    component: 'oil_cooling_circuit',
    active: false,
    affectedParameters: ['oilPressureBar', 'oilTempC', 'vibrationRmsMmS'],
  },
  {
    id: 'fault-4',
    type: 'CYLINDER_2_PREIGNITION',
    name: 'Cylinder #2 Incipient Pre-Ignition & Thermal Knock',
    description: 'Hot spot deposit in cylinder 2 combustion dome causing detonation onset at high boost levels (Knock Index 0.72).',
    severityPercent: 88,
    component: 'cylinder_2',
    active: false,
    affectedParameters: ['knockIndex', 'chtC[1]', 'vibrationRmsMmS'],
  },
];

export const INITIAL_ALERTS: AlertNotification[] = [
  {
    id: 'ALT-1092',
    timestamp: '11:42:15 UTC',
    uavId: 'UAV-RUSTOM-09',
    uavCallsign: 'RUSTOM-II-09 (VARUNA-4)',
    severity: 'WARNING',
    title: 'Cylinder #4 CHT Thermal Disparity (+18°C above Bank 1)',
    message: 'Adaptive Health Index detected 18°C gradient between Cyl 4 and Cyl 2. Physics-verified air baffle cooling deficit.',
    subsystem: 'Thermal / Cylinder Baffle',
    suggestedAction: 'Increase loiter airspeed by +8 kts to improve ram air cooling; monitor CHT trend.',
    acknowledged: false,
  },
  {
    id: 'ALT-1090',
    timestamp: '11:15:00 UTC',
    uavId: 'UAV-SWIFT-07',
    uavCallsign: 'SWIFT-ST-07 (GHATAK-PROTO)',
    severity: 'CRITICAL',
    title: 'Exhaust Valve Clearance Limit Reached (Ground Test)',
    message: 'Acoustic FFT harmonics indicated 4.8 mm/s vibration at 2X crank speed. Valve lash out of tolerance.',
    subsystem: 'Valvetrain / Camshaft',
    suggestedAction: 'Hold for scheduled Top-End overhaul; replace valve guide and shim tappet.',
    acknowledged: true,
    acknowledgedBy: 'Chief Propulsion Eng. K. Rao (DRDO ADE)',
    acknowledgedAt: '11:20:12 UTC',
  },
  {
    id: 'ALT-1088',
    timestamp: '10:50:33 UTC',
    uavId: 'UAV-TAPAS-201',
    uavCallsign: 'TAPAS-BH-201 (GARUDA-1)',
    severity: 'NOTICE',
    title: 'Self-Learning Threshold Updated (+1.5% Altitude Bias)',
    message: 'Continuous learning engine adapted CHT baseline for FL220 ambient pressure (-14°C OAT). Model v4.2.8 synchronized.',
    subsystem: 'Edge AI Inference',
    suggestedAction: 'Informational only. No pilot intervention required.',
    acknowledged: true,
    acknowledgedBy: 'AI Telemetry Daemon',
    acknowledgedAt: '10:50:34 UTC',
  },
];

export const ALL_23_INNOVATIONS = [
  { id: 1, title: 'Physics + AI Hybrid Model', category: 'Core Twin', desc: 'Dual thermodynamic physics simulation coupled with deep neural network for zero false-positive fault detection.', page: '/hybrid-verification' },
  { id: 2, title: 'Mission-Aware Remaining Useful Life (RUL)', category: 'Predictive', desc: 'Calculates dynamic engine component RUL based on real-time altitude, hot weather, and combat maneuvers.', page: '/ai-predictions' },
  { id: 3, title: 'Adaptive Health Index (AHI)', category: 'Health', desc: 'Dynamic health score updating with environmental pressure, engine wear state, and mission profile.', page: '/live-monitoring' },
  { id: 4, title: 'AI Smart Maintenance Advisor', category: 'Maintenance', desc: 'MIL-STD guided repair actions, spare parts allocation, and safe flight hour forecasting.', page: '/maintenance' },
  { id: 5, title: 'Digital Twin Confidence Score', category: 'Sync', desc: 'Real-time telemetry-to-model fidelity gauge showing 98.7% convergence rate.', page: '/digital-twin' },
  { id: 6, title: 'Mission Replay with AI Explanation', category: 'Analysis', desc: 'Black-box flight recording with synchronized AI narrative reasoning and event bookmarks.', page: '/mission-replay' },
  { id: 7, title: '3D Thermal & Stress Heat Map', category: '3D Twin', desc: 'Layered visual heat and structural load map across all 4 cylinders, turbo, and crankcase.', page: '/digital-twin' },
  { id: 8, title: 'Fault Injection Simulator', category: 'Testbed', desc: 'Interactive simulation bed for operator training and evaluating digital twin resilience.', page: '/fault-injection' },
  { id: 9, title: 'Explainable AI (XAI) Attribution', category: 'Transparency', desc: 'SHAP-style parameter contribution waterfalls explaining why an anomaly was flagged.', page: '/ai-predictions' },
  { id: 10, title: 'Fleet Squadron Monitoring', category: 'Fleet', desc: 'Simultaneous surveillance of multiple UAV aero piston engines across multiple air bases.', page: '/fleet' },
  { id: 11, title: 'Mission Risk Go / No-Go Engine', category: 'Mission', desc: 'Continuous probabilistic risk assessment factoring weather, terrain, and engine health.', page: '/mission-control' },
  { id: 12, title: 'Self-Learning Threshold Engine', category: 'Learning', desc: 'Replaces static thresholds with environmental and age-adapted dynamic envelope boundaries.', page: '/continuous-learning' },
  { id: 13, title: 'Engine Behaviour Fingerprint', category: 'Diagnostics', desc: 'Multi-dimensional acoustic, thermal, and pressure signature radar comparing against factory baseline.', page: '/fleet' },
  { id: 14, title: 'Physics-Based Fault Verification', category: 'Validation', desc: 'Cross-verifies AI neural net alerts against first-principles thermodynamic and gas equations.', page: '/hybrid-verification' },
  { id: 15, title: 'Failure Evolution Timeline', category: 'Predictive', desc: 'Cause-to-effect progressive degradation trajectory predicting failure stages 10-50 hours in advance.', page: '/ai-predictions' },
  { id: 16, title: 'Prediction Confidence Score', category: 'AI Metrics', desc: 'Statistical confidence interval reporting for all forecasted failure horizons.', page: '/ai-predictions' },
  { id: 17, title: 'Fault Severity Index (FSI)', category: 'Safety', desc: 'Military severity classification (Emergency, Critical, Major, Warning, Notice) with color coding.', page: '/alerts' },
  { id: 18, title: 'Tactical AI Chat Assistant', category: 'Operator UI', desc: 'Natural language GCS copilot capable of answering aerospace telemetry and maintenance queries.', page: '/dashboard' },
  { id: 19, title: 'Acoustic Voice Annunciator', category: 'Audio HUD', desc: 'Real-time spoken military alerts for hands-off situational awareness during high-stress ops.', page: '/alerts' },
  { id: 20, title: 'Continuous Edge Learning', category: 'AI Edge', desc: 'Autonomous edge model training based on accumulated squadron flight data telemetry.', page: '/continuous-learning' },
  { id: 21, title: 'Digital Maintenance Logbook & Passport', category: 'Logistics', desc: 'Immutable engine lifecycle history, flight hours, overhaul records, and parts compliance.', page: '/maintenance' },
  { id: 22, title: 'Multi-Agent AI Pipeline', category: 'Architecture', desc: 'Coordinated autonomous agents (Sensor, Health, Prediction, Physics, Maintenance, Command).', page: '/multi-agent' },
  { id: 23, title: 'Mission Optimization Advisor', category: 'Optimization', desc: 'Calculates optimal RPM/throttle flight profile to minimize thermal stress and extend loiter time.', page: '/mission-control' },
];

export const REPLAY_EVENT_BOOKMARKS = [
  {
    id: 'bm-1',
    frameIndex: 120,
    timestamp: 'T+00:15:30',
    title: 'Climb Phase: Full Throttle Boost Transition',
    eventCategory: 'FLIGHT_PHASE',
    description: 'Turbocharger wastegate modulated to 38% duty cycle at 12,000 FT to compensate for declining ambient air density.',
    aiNarrativeSummary: 'Engine operating parameters smoothly adapted to high altitude. Manifold pressure maintained at 35.8 inHg.',
  },
  {
    id: 'bm-2',
    frameIndex: 280,
    timestamp: 'T+00:42:15',
    title: 'Thermal Disparity: Cylinder #3 EGT Elevation',
    eventCategory: 'DIAGNOSTIC_ANOMALY',
    description: 'Exhaust Gas Temperature on Cylinder #3 rose to 818°C (+42°C above cohort average).',
    aiNarrativeSummary: 'Incipient fuel injector restriction detected by multi-agent health diagnostic. Physics model verified localized lean combustion.',
  },
  {
    id: 'bm-3',
    frameIndex: 450,
    timestamp: 'T+01:10:00',
    title: 'Loiter Orbit: Waypoint WP-04 Orbit Ingress',
    eventCategory: 'MISSION_WAYPOINT',
    description: 'MALE UAV established steady-state orbital surveillance at FL220 over Thar Desert sector.',
    aiNarrativeSummary: 'Engine throttled to 5,100 RPM loiter economy setting. Specific fuel consumption stabilized at 21.4 L/h.',
  },
  {
    id: 'bm-4',
    frameIndex: 680,
    timestamp: 'T+02:05:40',
    title: 'Evasive Power Burst: +3.0G Bank Turn',
    eventCategory: 'HIGH_STRESS',
    description: 'Sudden throttle excursion to 5,750 RPM during tactical evasive waypoint transition.',
    aiNarrativeSummary: 'Lubrication hydrodynamic oil pressure held steady at 4.35 bar. Zero pre-ignition knock or detonation observed.',
  },
];

export const DEMO_TOUR_STEPS: DemoTourStep[] = [
  {
    id: 1,
    title: 'DRDO Ground Control Station Dashboard',
    innovationNumber: 10,
    innovationName: 'Mission Overview & Multi-UAV Fleet Status',
    pageTarget: '/',
    highlightSelector: '#dashboard-overview',
    summary: 'Executive tactical dashboard displaying all active MALE UAVs (TAPAS-201, Archer-NG, Rustom-II), real-time Go/No-Go Mission Risk score, and health distributions.',
    defenceImpact: 'Provides Mission Commanders instantaneous fleet health status across national border sectors.',
    demonstrationAction: 'View the live telemetry ticker, UAV quick-switch selector, and tactical system health summary.',
  },
  {
    id: 2,
    title: 'High-Density Live SCADA Telemetry',
    innovationNumber: 3,
    innovationName: 'Adaptive Health Index & Multi-Sensor Instrumentation',
    pageTarget: '/live-monitoring',
    highlightSelector: '#telemetry-gauges',
    summary: 'Real-time monitoring of 4-cylinder CHT/EGT thermocouples, turbocharger boost pressure, high-frequency vibration FFT spectrum, and fuel/oil hydraulics.',
    defenceImpact: 'Enables propulsion engineers to spot micro-anomalies before mechanical degradation cascades into flight failure.',
    demonstrationAction: 'Inspect the live RPM gauge, 4-cylinder thermal bar graphs, and vibration harmonic spectrum.',
  },
  {
    id: 3,
    title: '3D Digital Twin & Thermal Heat Map',
    innovationNumber: 7,
    innovationName: 'Layered 3D Thermal & Structural Stress Model',
    pageTarget: '/digital-twin',
    highlightSelector: '#digital-twin-canvas',
    summary: 'High-fidelity interactive 3D aero engine visualization showing live cylinder temperatures, mechanical stress load gradients, and twin sync accuracy (98.7%).',
    defenceImpact: 'Transforms invisible internal combustion chamber pressures into an interactive, visually clear digital replica.',
    demonstrationAction: 'Click through engine components (Cylinders 1-4, Turbocharger, Crankcase) and toggle Thermal/Stress overlays.',
  },
  {
    id: 4,
    title: 'Physics + AI Hybrid Verification Engine',
    innovationNumber: 1,
    innovationName: 'First-Principles Thermodynamic & Neural Network Hybrid',
    pageTarget: '/hybrid-verification',
    highlightSelector: '#hybrid-engine-card',
    summary: 'Our primary USP: Combines physics-based thermodynamic gas equations with Deep Learning, achieving 0% false positives by cross-verifying all AI anomaly detections.',
    defenceImpact: 'Eliminates false alarms that cause costly mission aborts while ensuring 100% true fault capture.',
    demonstrationAction: 'Compare Physics Expected vs AI Predicted vs Actual Telemetry columns and inspect the verified badges.',
  },
  {
    id: 5,
    title: 'AI Prediction Center & Explainable AI (XAI)',
    innovationNumber: 2,
    innovationName: 'Mission-Aware Remaining Useful Life & SHAP Attribution',
    pageTarget: '/ai-predictions',
    highlightSelector: '#rul-matrix',
    summary: 'Dynamically computes Remaining Useful Life (RUL) under extreme envelopes (High Altitude 28,000ft, Desert Hot, Long Loiter) with SHAP parameter attribution.',
    defenceImpact: 'Allows commanders to safely extend or abort missions based on mission-specific engine wear calculations.',
    demonstrationAction: 'Explore the SHAP feature contribution waterfall and the 5-stage failure evolution timeline.',
  },
  {
    id: 6,
    title: 'Interactive Fault Injection Testbed',
    innovationNumber: 8,
    innovationName: 'Real-Time Failure Simulation & Twin Response',
    pageTarget: '/fault-injection',
    highlightSelector: '#fault-controls',
    summary: 'Allows evaluators to inject real aero piston faults (Turbo wastegate sticking, Injector clog, Oil pump cavitation, Pre-ignition knock) and observe GCS reaction.',
    defenceImpact: 'Validates system robustness and serves as advanced pilot/engineer training simulator.',
    demonstrationAction: 'Click "Inject Fault" on the Turbocharger Wastegate scenario to watch the live Digital Twin and alert system respond.',
  },
  {
    id: 7,
    title: 'AI Smart Maintenance & Digital Engine Passport',
    innovationNumber: 4,
    innovationName: 'MIL-STD Maintenance Advisor & Parts Inventory',
    pageTarget: '/maintenance',
    highlightSelector: '#maintenance-plan',
    summary: 'Prescribes precise maintenance actions, estimates required labor hours, reserves depot spare parts, and tracks immutable flight hours logbook.',
    defenceImpact: 'Reduces UAV turnaround time by 40% and prevents catastrophic in-flight engine seizures.',
    demonstrationAction: 'Review the pending maintenance queue and examine the complete digital passport for Engine Rotax 914-TC.',
  },
];
