version: '3.8'
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=aerosim
    ports:
      - "5432:5432"
    volumes:
      - ./backend/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
